# This file is part of LACI.
#
# LACI is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# LACI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with LACI.
# If not, see <https://www.gnu.org/licenses/>.
# The URL of your server (e.g. http://localhost:49871 or foobar.lndo.site) for browersync
#
# Copyright 2023-2024, Lone Star Legal Aid
#
BROWSERSYNC: 'https://laci.localhost'

# Gulp will reference these paths when it copies files
PATHS:
  # Path to built css folder
  dist: "css"
  # Path to main scss files and settings for subtheme
  scss: "scss/*.scss"
  # Path to subtheme scss files
  componentScss: "scss/**/*.scss"
  # Paths to Sass libraries, which can then be loaded with @import
  foundationScss:
    - "node_modules/foundation-sites/scss"
  # Path to custom JS
  js:
    "js/*.js"
  # Paths to Foundation JavaScript for webpack to bundle modules
  foundationJs:
    - "node_modules/foundation-sites/dist/js/*.js"
