<?php
/**
 * This file is part of LACI.
 *
 * LACI is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * LACI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with LACI.
 * If not, see <https://www.gnu.org/licenses/>.
 *
 * Copyright 2023-2026, Lone Star Legal Aid
 */

/**
 * @file
 * Add your custom theme override functions here.
 */

/**
 * Implements hook_preprocess_block().
 */
function lacitheme_preprocess_block(&$variables) {
}

/**
 * Implements template_preprocess_field().
 */
function lacitheme_preprocess_field(&$variables, $hook) {
}

/**
 * Implements template_preprocess_html().
 *
 * Adds additional classes.
 */
function lacitheme_preprocess_menu(&$variables) {
  $variables['theme_logo_url'] = \Drupal::service('file_url_generator')->generate(\Drupal::service('extension.list.theme')->getPath('lacitheme').'/logo.png');
}

/**
 * Implements template_preprocess_node.
 *
 * Add template suggestions and classes.
 */
function lacitheme_preprocess_node(&$variables) {


}

/**
 * Implements template_preprocess_page.
 *
 * Add convenience variables and template suggestions.
 */

function lacitheme_preprocess_page(&$variables) {
  if (empty($variables['laci_login_image_url'])) {
    $variables['laci_login_image_url'] = \Drupal::service('file_url_generator')->generate(\Drupal::service('extension.list.theme')->getPath('lacitheme').'/images/img-login-left.png');
  }
}


/**
 * Implements template_preprocess_views_view().
 */
function lacitheme_preprocess_views_view(&$variables) {
}
